import { adminColors } from '@/theme/admin';
import { adminDesign } from '@/theme/adminDesign';
import { spacing } from '@/theme/spacing';

/** Dashboard-local layout constants — colors reference shared admin tokens. */
export const dash = {
  bg: adminColors.canvasBg,
  text: adminDesign.colors.textPrimary,
  textSecondary: adminDesign.colors.textSecondary,
  brand: adminColors.primary,
  success: adminDesign.colors.success,
  warning: adminDesign.colors.warning,
  danger: adminDesign.colors.error,
  card: adminColors.cardBg,
  border: adminDesign.colors.border,
  searchFill: '#ECEEF2',
  pressed: '#F3F4F6',
  pagePad: adminDesign.layout.pagePadding,
  sectionGap: 18,
  cardGap: spacing.sm,
  cardPad: adminDesign.layout.cardPadding,
  compactPad: 14,
  heroPad: 14,
  tilePad: 10,
  sectionHeaderMb: spacing.xs,
  metricGap: 6,
  radiusHero: adminDesign.radius.card,
  radiusMd: 18,
  radiusSm: adminDesign.radius.input,
  radiusTile: adminDesign.radius.input,
  radiusPill: adminDesign.radius.chip,
  btnRadius: adminDesign.radius.button,
  heroMinH: 148,
  kpiH: 112,
  quickTileH: 88,
  accordionH: 74,
  searchH: 50,
  btnH: adminDesign.button.minHeight,
  livePillH: 26,
  chipH: 36,
  expiryPillH: 28,
  rowH: 74,
  avatar: 40,
  iconBox: 34,
  touch: adminDesign.layout.minTouch,
  shadow: {
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.035,
    shadowRadius: 6,
    elevation: 2,
  },
} as const;
