export const officerStrings = {
  list: {
    title: 'Officers',
    searchPlaceholder: 'Search team members…',
    emptyTitle: 'No officers found',
    emptySubtitle: 'Add your first team member to get started.',
    addOfficer: 'Add Officer',
    pullToRefresh: 'Pull to refresh',
    offlineCached: 'You are offline. Showing cached data.',
  },
  filters: {
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    blocked: 'Blocked',
  },
  kpi: {
    totalForce: 'Total Force',
    activeStatus: 'Active Status',
    available: 'Available',
    restricted: 'Restricted',
  },
  actions: {
    viewDetails: 'View Details',
    edit: 'Edit',
    block: 'Block',
    unblock: 'Unblock',
    delete: 'Delete',
    blockConfirmTitle: 'Block officer',
    blockConfirmMessage: (name: string) =>
      `Restrict ${name} from accessing the Officer app?`,
    unblockConfirmTitle: 'Unblock officer',
    unblockConfirmMessage: (name: string) => `Restore access for ${name}?`,
    deleteConfirmTitle: 'Delete officer',
    deleteConfirmMessage: (name: string) =>
      `Permanently remove ${name}? This cannot be undone.`,
  },
  detail: {
    tabs: {
      onboarding: 'Onboarding Details',
      contract: 'Contract',
      documents: 'Documents',
    },
    sections: {
      roleAssignment: 'Role Assignment',
      onboardingDetails: 'Onboarding Details',
      personalInfo: 'Personal Information',
      contactInfo: 'Contact Information',
      bankDetails: 'Bank Details',
      emergencyContacts: 'Emergency Contacts',
      education: 'Education',
      backgroundInfo: 'Background Information',
      positionExpectations: 'Position & Expectations',
      contractDetails: 'Contract Details',
      contractInfo: 'Contract Information',
      employmentDetails: 'Employment Details',
      salaryBreakdown: 'Salary Breakdown',
      bankPayout: 'Bank Details (Payout)',
      benefits: 'Benefits',
      credentials: 'Account Credentials',
    },
    labels: {
      assignedRole: 'Assigned Role',
      joiningDate: 'Joining date',
      permissionsFor: (role: string) => `Permissions for ${role}`,
      fullName: 'Full Name',
      dateOfBirth: 'Date of Birth',
      gender: 'Gender',
      bloodGroup: 'Blood Group',
      maritalStatus: 'Marital Status',
      email: 'Email',
      phone: 'Phone',
      alternatePhone: 'Alternate Phone',
      currentAddress: 'Current Address',
      permanentAddress: 'Permanent Address',
      city: 'City',
      state: 'State',
      pincode: 'Pincode',
      bankName: 'Bank Name',
      accountHolder: 'Account Holder Name',
      accountNumber: 'Account Number',
      ifsc: 'IFSC Code',
      emergencyContact: (n: number) => `Emergency Contact ${n}`,
      relationship: 'Relationship',
      address: 'Address',
      highestQualification: 'Highest Qualification',
      university: 'University/College',
      graduationYear: 'Graduation Year',
      criminalRecord: 'Criminal Record',
      healthIssues: 'Health Issues',
      details: 'Details',
      positionApplied: 'Position Applied',
      expectedSalary: 'Expected Salary',
      joiningPreference: 'Joining Date Preference',
      contractNumber: 'Contract Number',
      contractType: 'Contract Type',
      contractStatus: 'Status',
      startDate: 'Start Date',
      position: 'Position',
      designation: 'Designation',
      department: 'Department',
      reportingTo: 'Reporting To',
      workLocation: 'Work Location',
      workingHours: 'Working Hours/Day',
      weeklyOff: 'Weekly Off Days',
      leaveEntitlement: 'Leave Entitlement/Year',
      basicSalary: 'Basic Salary',
      hra: 'HRA',
      transport: 'Transport Allowance',
      otherAllowances: 'Other Allowances',
      totalSalary: 'Total Salary',
      perMonth: '/month',
      healthInsurance: 'Health Insurance',
      pfApplicable: 'PF Applicable',
      esicApplicable: 'ESIC Applicable',
      loginEmail: 'Login Email',
      passwordMethod: 'Password Method',
      revealPassword: 'Reveal Password',
      resetPassword: 'Reset Password',
      allowAdminView: 'Admin can view password',
    },
    documentStatus: {
      uploaded: 'Uploaded',
      notUploaded: 'Not Uploaded',
    },
    na: 'N/A',
    yes: 'Yes',
    no: 'No',
  },
  form: {
    steps: {
      personal: { title: 'Personal Info', subtitle: 'Name, DOB, gender, photo' },
      contact: { title: 'Contact & Bank', subtitle: 'Address, bank, emergency contacts' },
      contract: { title: 'Contract & Role', subtitle: 'Role, salary, credentials' },
      documents: { title: 'Documents', subtitle: 'ID, photo, resume' },
    },
    copyToPermanent: 'Copy to permanent address',
    totalSalary: (amount: number) => `Total: ₹${amount.toLocaleString('en-IN')}/month`,
    credentials: {
      title: 'Account Credentials',
      modeAuto: 'Auto-generate password',
      modeManual: 'Set password manually',
      credentialsEmail: 'Credentials email (optional)',
      credentialsEmailHint: 'Defaults to officer email if empty',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      allowAdminView: 'Allow admin to view password in officer panel',
    },
    submit: 'Submit',
    next: 'Next',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    unsavedTitle: 'Unsaved changes',
    unsavedMessage: 'You have unsaved changes. Discard them?',
    discard: 'Discard',
    stay: 'Stay',
    successTitle: 'Officer created',
    successMessage: (name: string) => `${name} has been added successfully.`,
    credentialsCreated: 'Save these credentials — they will not be shown again:',
  },
} as const;
