export type NotificationPriority = 'Low' | 'Normal' | 'High' | 'Urgent';

export type NotificationStatus =
  | 'draft'
  | 'scheduled'
  | 'sending'
  | 'sent'
  | 'partially_failed'
  | 'failed'
  | 'cancelled';

export type EventType =
  | 'none'
  | 'systemAlert'
  | 'accountUpdate'
  | 'promotional'
  | 'paymentReminder'
  | 'maintenanceAlert'
  | 'planExpiry'
  | 'newOffer'
  | 'serviceDisruption'
  | 'requestUpdate'
  | 'ticketUpdate'
  | 'welcomeMessage'
  | 'custom';

export type AudienceType =
  | 'all_users'
  | 'active_users'
  | 'inactive_users'
  | 'specific_plan'
  | 'specific_area'
  | 'specific_users'
  | 'officers'
  | 'admins'
  | 'all_staff'
  | 'custom_segment';

export interface AudienceConfig {
  type: AudienceType;
  planId?: string;
  planName?: string;
  area?: string;
  userIds?: string[];
  userNames?: string[];
  officerIds?: string[];
  estimatedCount: number;
  resolvedAt?: Date;
}

export interface ScheduleConfig {
  isScheduled: boolean;
  scheduledAt: Date | null;
  timezone: string;
  sentAt: Date | null;
}

export interface DeliveryStats {
  totalTargeted: number;
  totalSent: number;
  totalDelivered: number;
  totalFailed: number;
  totalOpened: number;
  failedTokens: string[];
  deliveryRate: number;
  openRate: number;
  processingMs: number;
}

export interface NotificationRecipient {
  userId: string;
  userName: string;
  userType: 'customer' | 'officer' | 'admin';
  pushToken: string | null;
  deliveryStatus: 'pending' | 'sent' | 'delivered' | 'failed' | 'no_token';
  failureReason?: string;
  sentAt?: Date;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  status: NotificationStatus;
  audience: AudienceConfig;
  schedule: ScheduleConfig;
  delivery: DeliveryStats | null;
  recipients: NotificationRecipient[];
  createdAt: Date;
  updatedAt: Date;
  createdById: string;
  createdByName: string;
  isDraft: boolean;
  isAutoGenerated?: boolean;
  tags: string[];
  deepLinkUrl?: string;
  imageUrl?: string;
  linkedRequestId?: string;
  linkedTicketId?: string;
  linkedPlanId?: string;
}

export interface NotificationTemplate {
  id: string;
  name: string;
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  audienceType: AudienceType;
  isSystem: boolean;
  createdAt: Date;
}

export interface NotificationFilters {
  tab: 'drafts' | 'sent';
  searchQuery: string;
  sortBy: 'newest' | 'oldest' | 'title_az';
  priority: NotificationPriority | 'all';
  eventType: EventType | 'all';
  audienceType: AudienceType | 'all';
  dateRange: { from: Date | null; to: Date | null };
}

export interface CreateNotificationFormData {
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  audience: Omit<AudienceConfig, 'estimatedCount' | 'resolvedAt'>;
  schedule: Omit<ScheduleConfig, 'sentAt'>;
  tags: string[];
  deepLinkUrl: string;
  imageUrl: string;
  templateId: string | null;
}

export interface SendProgress {
  total: number;
  sent: number;
  failed: number;
  percent: number;
}

export const NOTIFICATION_PRIORITIES: NotificationPriority[] = ['Low', 'Normal', 'High', 'Urgent'];

export const EVENT_TYPE_OPTIONS: { value: EventType; label: string; icon: string }[] = [
  { value: 'none', label: 'None (General)', icon: 'remove-circle-outline' },
  { value: 'systemAlert', label: 'System Alert', icon: 'alert-circle-outline' },
  { value: 'accountUpdate', label: 'Account Update', icon: 'person-outline' },
  { value: 'promotional', label: 'Promotional', icon: 'gift-outline' },
  { value: 'paymentReminder', label: 'Payment Reminder', icon: 'card-outline' },
  { value: 'maintenanceAlert', label: 'Maintenance Alert', icon: 'construct-outline' },
  { value: 'planExpiry', label: 'Plan Expiry Warning', icon: 'time-outline' },
  { value: 'newOffer', label: 'New Offer / Plan', icon: 'pricetag-outline' },
  { value: 'serviceDisruption', label: 'Service Disruption', icon: 'wifi-off-outline' },
  { value: 'requestUpdate', label: 'Request Status Update', icon: 'document-text-outline' },
  { value: 'ticketUpdate', label: 'Ticket Update', icon: 'ticket-outline' },
  { value: 'welcomeMessage', label: 'Welcome Message', icon: 'hand-right-outline' },
  { value: 'custom', label: 'Custom', icon: 'create-outline' },
];

export const AUDIENCE_TYPE_OPTIONS: { value: AudienceType; label: string; icon: string }[] = [
  { value: 'all_users', label: 'All Users', icon: 'people' },
  { value: 'active_users', label: 'Active Users', icon: 'checkmark-circle' },
  { value: 'inactive_users', label: 'Inactive Users', icon: 'close-circle' },
  { value: 'specific_plan', label: 'Specific Plan', icon: 'cellular' },
  { value: 'specific_area', label: 'Specific Area', icon: 'location' },
  { value: 'specific_users', label: 'Specific User(s)', icon: 'person' },
  { value: 'officers', label: 'Officers', icon: 'shield' },
  { value: 'all_staff', label: 'All Staff', icon: 'people-circle' },
];
