/**
 * Shared logical SQL dump + upload for admin-backup-export and daily-backup-cron.
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.42.0';

export const MAX_ROWS_PER_TABLE = 50_000;
export const EXCLUDED_TABLES = new Set([
  'schema_migrations',
  'spatial_ref_sys',
  'admin_backup_files',
]);

export function getDatabaseUrl(): string {
  return Deno.env.get('DATABASE_URL') ?? Deno.env.get('SUPABASE_DB_URL') ?? '';
}

/** Dynamic import so `pg` is not evaluated at worker boot (static import caused BOOT_ERROR on Edge). */
export async function getPool() {
  const pg = await import('npm:pg@8.11.3');
  // npm `pg` is CommonJS; under Deno the constructor lives on `default.Pool`, not a top-level named export.
  const mod = pg as { default?: { Pool?: unknown }; Pool?: unknown };
  const PoolCtor = mod.default?.Pool ?? mod.Pool;
  if (typeof PoolCtor !== 'function') {
    throw new Error('Could not load pg.Pool from npm:pg (unexpected module shape)');
  }
  const DATABASE_URL = getDatabaseUrl();
  if (!DATABASE_URL) {
    throw new Error(
      'DATABASE_URL (or SUPABASE_DB_URL) is not set. Add it in Edge Function secrets: Project Settings → Database → Connection string (URI).',
    );
  }
  return new (PoolCtor as new (c: Record<string, unknown>) => unknown)({
    connectionString: DATABASE_URL,
    max: 1,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 25_000,
  });
}

export async function buildLogicalSqlDump(): Promise<string> {
  const pool = await getPool();
  const client = await pool.connect();
  const chunks: string[] = [];
  chunks.push('-- Prime Fibernet logical backup (public schema)');
  chunks.push('-- Generated by admin backup Edge Function (not pg_dump).');
  chunks.push(`-- Max ${MAX_ROWS_PER_TABLE} rows per table.`);
  chunks.push('BEGIN;');
  chunks.push('SET session_replication_role = replica;');

  try {
    const { rows: tables } = await client.query<{ table_name: string }>(
      `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `,
    );

    for (const { table_name } of tables) {
      if (EXCLUDED_TABLES.has(table_name)) continue;
      const safeName = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(table_name) ? table_name : null;
      if (!safeName) continue;

      const { rows: colRows } = await client.query<{
        column_name: string;
        data_type: string;
        udt_name: string;
      }>(
        `
        SELECT column_name, data_type, udt_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY ordinal_position
      `,
        [safeName],
      );
      if (colRows.length === 0) continue;

      const colList = colRows.map((c) => `"${c.column_name.replace(/"/g, '""')}"`).join(', ');
      const { rows: dataRows, rowCount } = await client.query(
        `SELECT * FROM public."${safeName}" LIMIT $1`,
        [MAX_ROWS_PER_TABLE],
      );

      chunks.push(`\n-- TABLE public.${safeName} (${rowCount} rows)`);
      if (!dataRows.length) continue;

      const batch = 50;
      for (let i = 0; i < dataRows.length; i += batch) {
        const slice = dataRows.slice(i, i + batch);
        const valuesSql = slice
          .map((row) => {
            const vals = colRows.map((c) => formatSqlValue((row as Record<string, unknown>)[c.column_name], c));
            return `(${vals.join(', ')})`;
          })
          .join(',\n');
        chunks.push(`INSERT INTO public."${safeName}" (${colList}) VALUES\n${valuesSql};`);
      }
    }

    chunks.push('SET session_replication_role = DEFAULT;');
    chunks.push('COMMIT;');
    return chunks.join('\n');
  } catch (e) {
    chunks.push('ROLLBACK;');
    throw e;
  } finally {
    client.release();
    await pool.end();
  }
}

function formatSqlValue(val: unknown, col: { data_type: string; udt_name: string }): string {
  if (val === null || val === undefined) return 'NULL';
  const dt = col.data_type;
  const udt = col.udt_name;

  if (dt === 'bytea' || udt === 'bytea') {
    if (val instanceof Uint8Array) {
      const hex = Array.from(val).map((b) => b.toString(16).padStart(2, '0')).join('');
      return `decode('${hex}', 'hex')`;
    }
    if (typeof val === 'object' && val !== null && 'type' in (val as object) && (val as { type: string }).type === 'Buffer') {
      const arr = (val as { data: number[] }).data;
      const hex = arr.map((b) => b.toString(16).padStart(2, '0')).join('');
      return `decode('${hex}', 'hex')`;
    }
    return 'NULL';
  }

  if (typeof val === 'boolean') return val ? 'true' : 'false';
  if (typeof val === 'number') {
    if (Number.isFinite(val)) return String(val);
    return 'NULL';
  }

  if (val instanceof Date) {
    return `'${val.toISOString()}'::timestamptz`;
  }

  if (typeof val === 'object') {
    if (dt === 'json' || dt === 'jsonb' || udt === 'json' || udt === 'jsonb') {
      return `'${JSON.stringify(val).replace(/'/g, "''")}'::jsonb`;
    }
    return `'${JSON.stringify(val).replace(/'/g, "''")}'::text`;
  }

  const s = String(val);
  if (dt === 'uuid' || udt === 'uuid') {
    return `'${s.replace(/'/g, "''")}'::uuid`;
  }
  if (dt === 'integer' || dt === 'bigint' || dt === 'smallint' || dt === 'numeric' || dt === 'real' || dt === 'double precision') {
    if (/^-?\d+(\.\d+)?$/.test(s)) return s;
  }

  return `'${s.replace(/'/g, "''")}'`;
}

export function formatTimestamp(): string {
  const d = new Date();
  const p = (n: number) => n.toString().padStart(2, '0');
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

export type SupabaseAdmin = ReturnType<typeof createClient>;

export async function uploadSqlBackup(
  admin: SupabaseAdmin,
  args: {
    storagePath: string;
    filename: string;
    bytes: Uint8Array;
    createdBy: string | null;
  },
): Promise<{ id: string }> {
  const up = await admin.storage.from('admin-backups').upload(args.storagePath, args.bytes, {
    contentType: 'application/sql',
    upsert: true,
  });
  if (up.error) throw up.error;

  const { data: ins, error: insErr } = await admin
    .from('admin_backup_files')
    .insert({
      filename: args.filename,
      size_bytes: args.bytes.length,
      storage_path: args.storagePath,
      created_by: args.createdBy,
      content_type: 'application/sql',
    })
    .select('id')
    .single();
  if (insErr) throw insErr;
  return { id: ins?.id ?? '' };
}
