import type { CustomerTheme } from './types';

/** Prime Light Broadband — Stitch light theme for customer app */
export const primeLight: CustomerTheme = {
  colors: {
    background: '#F8F9FF',
    surface: '#F8F9FF',
    surfaceContainer: '#E5EEFF',
    surfaceContainerLow: '#EFF4FF',
    surfaceContainerHigh: '#DCE9FF',
    surfaceVariant: '#D3E4FE',
    bgDeep: '#F8F9FF',
    bgSurface: '#FFFFFF',
    bgGlass: 'rgba(255,255,255,0.92)',
    primary: '#0037B0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#1D4ED8',
    onPrimaryContainer: '#CAD3FF',
    secondary: '#735C00',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FED01B',
    tertiary: '#7F2500',
    accentPrimary: '#1D4ED8',
    accentPrimaryMuted: 'rgba(29,78,216,0.12)',
    accentGlow: '#0037B0',
    accentSuccess: '#059669',
    accentWarning: '#D97706',
    accentDanger: '#BA1A1A',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    onError: '#FFFFFF',
    textPrimary: '#0B1C30',
    textSecondary: '#434655',
    textMuted: '#747686',
    onSurface: '#0B1C30',
    onSurfaceVariant: '#434655',
    outline: '#747686',
    outlineVariant: '#C4C5D7',
    borderSubtle: '#E2E8F0',
    borderGlass: '#C4C5D7',
    overlay: 'rgba(11,28,48,0.4)',
    white: '#FFFFFF',
  },
  gradients: {
    card: ['#FFFFFF', '#F8FAFC'] as const,
    hero: ['#EFF4FF', '#F8F9FF'] as const,
    canvas: ['#F8F9FF', '#EFF4FF'] as const,
    ambientPrimary: ['rgba(29,78,216,0.06)', 'transparent'] as const,
    ambientSecondary: ['rgba(254,208,27,0.08)', 'transparent'] as const,
  },
  blur: {
    cardIntensity: 0,
    barIntensity: 80,
  },
  spacing: {
    base: 4,
    xs: 8,
    sm: 16,
    md: 24,
    lg: 40,
    xl: 48,
    xxl: 32,
    xxxl: 48,
    marginMobile: 16,
    gutter: 24,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  shadow: {
    cardGlow: {
      shadowColor: '#0B1C30',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 20,
      elevation: 4,
    },
    primaryGlow: {
      shadowColor: '#1D4ED8',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
  },
  typography: {
    displayLg: { fontSize: 36, fontWeight: '700' as const, lineHeight: 44, letterSpacing: -0.72 },
    displayMd: { fontSize: 30, fontWeight: '600' as const, lineHeight: 38, letterSpacing: -0.3 },
    bodyLg: { fontSize: 18, fontWeight: '400' as const, lineHeight: 28 },
    body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodyMedium: { fontSize: 16, fontWeight: '500' as const, lineHeight: 24 },
    caption: { fontSize: 12, fontWeight: '600' as const, lineHeight: 16 },
    label: { fontSize: 12, fontWeight: '600' as const, lineHeight: 16, letterSpacing: 0.5 },
    mono: { fontSize: 20, fontWeight: '600' as const, lineHeight: 24, letterSpacing: 0.4 },
    monoMd: { fontSize: 14, fontWeight: '500' as const, lineHeight: 20 },
  },
  motion: {
    staggerMs: 100,
    fadeDurationMs: 350,
  },
  fonts: {
    display: 'Inter_700Bold',
    body: 'Inter_400Regular',
    bodyMedium: 'Inter_500Medium',
    bodySemiBold: 'Inter_700Bold',
    mono: 'JetBrainsMono_400Regular',
    monoBold: 'JetBrainsMono_700Bold',
  },
  appearance: 'light',
  blurTint: 'light',
  useGlassBlur: false,
};
