import type { CustomerTheme } from './types';

import { customerLayoutTokens } from './customerLayout';

/** Prime Light Broadband — Stitch light theme for customer app */
export const primeLight: CustomerTheme = {
  ...customerLayoutTokens,
  colors: {
    background: '#F8F9FF',
    surface: '#F8F9FF',
    surfaceContainer: '#E5EEFF',
    surfaceContainerLow: '#EFF4FF',
    surfaceContainerHigh: '#DCE9FF',
    surfaceVariant: '#D3E4FE',
    bgDeep: '#F8F9FF',
    bgSurface: '#FFFFFF',
    bgGlass: 'rgba(255,255,255,0.92)',
    primary: '#0037B0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#1D4ED8',
    onPrimaryContainer: '#CAD3FF',
    secondary: '#735C00',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FED01B',
    tertiary: '#7F2500',
    accentPrimary: '#1D4ED8',
    accentPrimaryMuted: 'rgba(29,78,216,0.12)',
    accentGlow: '#0037B0',
    accentSuccess: '#059669',
    accentWarning: '#D97706',
    accentDanger: '#BA1A1A',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    onError: '#FFFFFF',
    textPrimary: '#0B1C30',
    textSecondary: '#434655',
    textMuted: '#747686',
    onSurface: '#0B1C30',
    onSurfaceVariant: '#434655',
    outline: '#747686',
    outlineVariant: '#C4C5D7',
    borderSubtle: '#E2E8F0',
    borderGlass: '#C4C5D7',
    cardBorder: '#C4C5D7',
    inputFieldBg: '#FFFFFF',
    inputFieldBorder: '#E2E8F0',
    readOnlyFieldBg: '#F1F5F9',
    readOnlyFieldBorder: '#CBD5E1',
    dividerSubtle: '#E2E8F0',
    chipActiveBg: 'rgba(29,78,216,0.12)',
    chipActiveBorder: '#1D4ED8',
    chipInactiveBg: '#FFFFFF',
    overlay: 'rgba(11,28,48,0.4)',
    white: '#FFFFFF',
  },
  gradients: {
    card: ['#FFFFFF', '#F8FAFC'] as const,
    hero: ['#EFF4FF', '#F8F9FF'] as const,
    canvas: ['#F8F9FF', '#EFF4FF'] as const,
    ambientPrimary: ['rgba(29,78,216,0.06)', 'transparent'] as const,
    ambientSecondary: ['rgba(254,208,27,0.08)', 'transparent'] as const,
  },
  blur: {
    cardIntensity: 0,
    barIntensity: 80,
  },
  shadow: {
    cardGlow: {
      shadowColor: '#0B1C30',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 20,
      elevation: 4,
    },
    primaryGlow: {
      shadowColor: '#1D4ED8',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
  },
  appearance: 'light',
  blurTint: 'light',
  useGlassBlur: false,
};
