export { baseApi } from './baseApi';
export { getSupabase, getStoredAccessToken, registerFcmToken, supabaseBaseQuery } from './supabase';
export type { TypedSupabaseClient, SupabaseBaseQueryArg, SupabaseBaseQueryError } from './supabase';

import './authApi';
import './plansApi';
import './subscriptionsApi';
import './paymentsApi';
import './requestsApi';
import './officersApi';
import './analyticsApi';
import './adminDashboardApi';
import './adminUsersApi';
import './adminOfficersApi';
import './adminFinanceApi';
import './adminHrApi';
import './adminInventoryApi';
import './adminReportsApi';
import './adminMapApi';
import './adminRolesApi';
import './adminSettingsApi';
import './attendanceApi';

export * from './authApi';
export * from './plansApi';
export * from './subscriptionsApi';
export * from './paymentsApi';
export * from './requestsApi';
export * from './officersApi';
export * from './analyticsApi';
export * from './adminDashboardApi';
export * from './adminUsersApi';
export * from './adminOfficersApi';
export * from './adminFinanceApi';
export * from './adminHrApi';
export * from './adminInventoryApi';
export * from './adminReportsApi';
export * from './adminMapApi';
export * from './adminRolesApi';
export * from './adminSettingsApi';
export * from './attendanceApi';
