import type { RealtimeChannel } from '@supabase/supabase-js';

import { registerFcmToken } from '@/services/api/supabase';
import { getSupabase } from '@/services/supabase';
import type {
  AppNotification,
  AudienceConfig,
  CreateNotificationFormData,
  DeliveryStats,
  EventType,
  NotificationPriority,
  NotificationRecipient,
  NotificationStatus,
  NotificationTemplate,
} from '@/types/notifications';
import {
  formDataToDbPayload,
  replaceTemplateVars,
  resolveAudienceCount,
} from '@/utils/notificationUtils';
import type { SendProgressCallback } from '@/utils/pushDelivery';

type BroadcastRow = Record<string, unknown>;

type PostgrestErrorLike = { code?: string; message?: string };

function isMissingBroadcastTable(error: PostgrestErrorLike): boolean {
  return (
    error.code === 'PGRST205' &&
    (error.message?.includes('broadcast_notifications') ?? false)
  );
}

const notificationsRealtimeListeners = new Set<(notifications: AppNotification[]) => void>();
let notificationsRealtimeChannel: RealtimeChannel | null = null;
let notificationsRealtimeFailed = false;
let broadcastTableUnavailable = false;

async function notifyNotificationsRealtimeListeners() {
  try {
    const notifications = await fetchNotifications();
    for (const listener of notificationsRealtimeListeners) {
      listener(notifications);
    }
  } catch {
    // polling fallback handles refresh
  }
}

async function requireSession() {
  const client = getSupabase();
  const { data, error } = await client.auth.getSession();
  if (error) throw error;
  if (!data.session) throw new Error('Please sign in to manage notifications.');
  return { client, session: data.session };
}

function parseDate(value: unknown): Date | null {
  if (!value) return null;
  const d = new Date(String(value));
  return Number.isNaN(d.getTime()) ? null : d;
}

function mapRowToAudience(row: BroadcastRow): AudienceConfig {
  return {
    type: String(row.audience_type ?? 'all_users') as AudienceConfig['type'],
    planId: row.audience_plan_id ? String(row.audience_plan_id) : undefined,
    planName: row.audience_plan_name ? String(row.audience_plan_name) : undefined,
    area: row.audience_area ? String(row.audience_area) : undefined,
    userIds: Array.isArray(row.audience_user_ids)
      ? (row.audience_user_ids as string[]).map(String)
      : undefined,
    userNames: Array.isArray(row.audience_user_names)
      ? (row.audience_user_names as string[]).map(String)
      : undefined,
    officerIds: Array.isArray(row.audience_officer_ids)
      ? (row.audience_officer_ids as string[]).map(String)
      : undefined,
    estimatedCount: Number(row.audience_estimated_count ?? 0),
  };
}

function mapRowToDelivery(row: BroadcastRow): DeliveryStats | null {
  if (row.is_draft) return null;
  const totalSent = Number(row.total_sent ?? 0);
  const totalDelivered = Number(row.total_delivered ?? 0);
  return {
    totalTargeted: Number(row.total_targeted ?? 0),
    totalSent,
    totalDelivered,
    totalFailed: Number(row.total_failed ?? 0),
    totalOpened: Number(row.total_opened ?? 0),
    failedTokens: Array.isArray(row.failed_tokens) ? (row.failed_tokens as string[]) : [],
    deliveryRate: Number(row.delivery_rate ?? 0),
    openRate: Number(row.open_rate ?? 0),
    processingMs: Number(row.processing_ms ?? 0),
  };
}

export function mapRowToAppNotification(row: BroadcastRow, recipients: NotificationRecipient[] = []): AppNotification {
  return {
    id: String(row.id),
    title: String(row.title ?? ''),
    message: String(row.message ?? ''),
    priority: String(row.priority ?? 'Normal') as NotificationPriority,
    eventType: String(row.event_type ?? 'none') as EventType,
    status: String(row.status ?? 'draft') as NotificationStatus,
    audience: mapRowToAudience(row),
    schedule: {
      isScheduled: Boolean(row.is_scheduled),
      scheduledAt: parseDate(row.scheduled_at),
      timezone: String(row.timezone ?? 'Asia/Kolkata'),
      sentAt: parseDate(row.sent_at),
    },
    delivery: mapRowToDelivery(row),
    recipients,
    createdAt: parseDate(row.created_at) ?? new Date(),
    updatedAt: parseDate(row.updated_at) ?? new Date(),
    createdById: String(row.created_by_id ?? ''),
    createdByName: String(row.created_by_name ?? ''),
    isDraft: Boolean(row.is_draft),
    isAutoGenerated: Boolean(row.is_auto_generated),
    tags: Array.isArray(row.tags) ? (row.tags as string[]) : [],
    deepLinkUrl: row.deep_link_url ? String(row.deep_link_url) : undefined,
    imageUrl: row.image_url ? String(row.image_url) : undefined,
    linkedRequestId: row.linked_request_id ? String(row.linked_request_id) : undefined,
    linkedTicketId: row.linked_ticket_id ? String(row.linked_ticket_id) : undefined,
    linkedPlanId: row.linked_plan_id ? String(row.linked_plan_id) : undefined,
  };
}

async function fetchRecipientsForNotification(notificationId: string): Promise<NotificationRecipient[]> {
  const { client } = await requireSession();
  const { data, error } = await client
    .from('notification_recipients')
    .select('*')
    .eq('notification_id', notificationId)
    .order('created_at', { ascending: true });
  if (error) throw error;

  return (data ?? []).map((row) => ({
    userId: String(row.user_id),
    userName: String(row.user_name),
    userType: String(row.user_type) as NotificationRecipient['userType'],
    pushToken: row.push_token ? String(row.push_token) : null,
    deliveryStatus: String(row.delivery_status ?? 'pending') as NotificationRecipient['deliveryStatus'],
    failureReason: row.failure_reason ? String(row.failure_reason) : undefined,
    sentAt: parseDate(row.sent_at) ?? undefined,
  }));
}

export async function fetchNotifications(): Promise<AppNotification[]> {
  if (broadcastTableUnavailable) return [];

  const { client } = await requireSession();
  const { data, error } = await client
    .from('broadcast_notifications')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) {
    if (isMissingBroadcastTable(error)) {
      broadcastTableUnavailable = true;
      return [];
    }
    throw error;
  }
  broadcastTableUnavailable = false;
  return (data ?? []).map((row) => mapRowToAppNotification(row as BroadcastRow));
}

export async function fetchDrafts(): Promise<AppNotification[]> {
  const all = await fetchNotifications();
  return all.filter((n) => n.isDraft);
}

export async function fetchSentHistory(): Promise<AppNotification[]> {
  const all = await fetchNotifications();
  return all.filter((n) => !n.isDraft);
}

export async function fetchNotificationById(id: string): Promise<AppNotification> {
  const { client } = await requireSession();
  const { data, error } = await client.from('broadcast_notifications').select('*').eq('id', id).maybeSingle();
  if (error) throw error;
  if (!data) throw new Error('Notification not found');
  const recipients = await fetchRecipientsForNotification(id);
  return mapRowToAppNotification(data as BroadcastRow, recipients);
}

export async function createNotification(
  data: CreateNotificationFormData,
  admin: { id: string; name: string },
): Promise<AppNotification> {
  const { client } = await requireSession();
  const estimatedCount = await resolveAudienceCount(data.audience);
  const payload = formDataToDbPayload(data, admin, {
    audience_estimated_count: estimatedCount,
    is_draft: true,
    status: 'draft',
  });

  const { data: row, error } = await client.from('broadcast_notifications').insert(payload).select('*').single();
  if (error) throw error;
  return mapRowToAppNotification(row as BroadcastRow);
}

export async function updateNotification(
  id: string,
  data: Partial<CreateNotificationFormData>,
  admin: { id: string; name: string },
): Promise<AppNotification> {
  const { client } = await requireSession();
  const estimatedCount = data.audience ? await resolveAudienceCount(data.audience) : undefined;
  const payload = formDataToDbPayload(data, admin, {
    ...(estimatedCount !== undefined ? { audience_estimated_count: estimatedCount } : {}),
  });

  const { data: row, error } = await client
    .from('broadcast_notifications')
    .update(payload)
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return mapRowToAppNotification(row as BroadcastRow);
}

export async function saveDraft(
  data: CreateNotificationFormData,
  admin: { id: string; name: string },
  existingId?: string,
): Promise<AppNotification> {
  if (existingId) {
    const updated = await updateNotification(existingId, data, admin);
    await getSupabase()
      .from('broadcast_notifications')
      .update({ is_draft: true, status: 'draft' })
      .eq('id', existingId);
    return { ...updated, isDraft: true, status: 'draft' };
  }
  return createNotification(data, admin);
}

export async function deleteDraft(id: string): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client.from('broadcast_notifications').delete().eq('id', id).eq('is_draft', true);
  if (error) throw error;
}

export async function deleteFromHistory(id: string): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client.from('broadcast_notifications').delete().eq('id', id).eq('is_draft', false);
  if (error) throw error;
}

export async function scheduleNotification(id: string, scheduledAt: Date): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client
    .from('broadcast_notifications')
    .update({
      status: 'scheduled',
      is_scheduled: true,
      scheduled_at: scheduledAt.toISOString(),
      is_draft: false,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);
  if (error) throw error;
}

export async function cancelScheduled(id: string): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client
    .from('broadcast_notifications')
    .update({
      status: 'draft',
      is_scheduled: false,
      is_draft: true,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);
  if (error) throw error;
}

export async function fetchDueScheduledNotifications(): Promise<AppNotification[]> {
  if (broadcastTableUnavailable) return [];

  try {
    const { client } = await requireSession();
    const now = new Date().toISOString();
    const { data, error } = await client
      .from('broadcast_notifications')
      .select('*')
      .eq('status', 'scheduled')
      .lte('scheduled_at', now);
    if (error) {
      if (isMissingBroadcastTable(error)) {
        broadcastTableUnavailable = true;
        return [];
      }
      throw error;
    }
    return (data ?? []).map((row) => mapRowToAppNotification(row as BroadcastRow));
  } catch {
    return [];
  }
}

export async function sendNotification(
  id: string,
  _admin: { id: string; name: string },
  onProgress?: SendProgressCallback,
): Promise<AppNotification> {
  const { client } = await requireSession();
  const notification = await fetchNotificationById(id);
  const estimatedCount = notification.audience.estimatedCount || (await resolveAudienceCount(notification.audience));

  onProgress?.(0, 0, estimatedCount);

  const { data, error } = await client.functions.invoke('send-broadcast-notification', {
    body: { notificationId: id },
  });
  if (error) throw new Error(error.message ?? 'Failed to send notification');
  if (data && typeof data === 'object' && 'error' in data && data.error) {
    throw new Error(String(data.error));
  }

  const delivered = Number((data as { totalDelivered?: number })?.totalDelivered ?? 0);
  const targeted = Number((data as { totalTargeted?: number })?.totalTargeted ?? estimatedCount);
  onProgress?.(delivered, Math.max(0, targeted - delivered), targeted);

  return fetchNotificationById(id);
}

export async function resendNotification(
  id: string,
  admin: { id: string; name: string },
): Promise<AppNotification> {
  const original = await fetchNotificationById(id);
  const formData: CreateNotificationFormData = {
    title: original.title,
    message: original.message,
    priority: original.priority,
    eventType: original.eventType,
    audience: {
      type: original.audience.type,
      planId: original.audience.planId,
      planName: original.audience.planName,
      area: original.audience.area,
      userIds: original.audience.userIds,
      userNames: original.audience.userNames,
      officerIds: original.audience.officerIds,
    },
    schedule: { isScheduled: false, scheduledAt: null, timezone: original.schedule.timezone },
    tags: original.tags,
    deepLinkUrl: original.deepLinkUrl ?? '',
    imageUrl: original.imageUrl ?? '',
    templateId: null,
  };

  const created = await createNotification(formData, admin);
  const { client } = await requireSession();
  await client.from('broadcast_notifications').update({ is_draft: false, status: 'sending' }).eq('id', created.id);
  return sendNotification(created.id, admin);
}

export type AutomationChannels = {
  push: boolean;
  in_app: boolean;
  email: boolean;
  sms: boolean;
};

export type AutomationRule = {
  id: string;
  eventKey: string;
  label: string;
  description: string | null;
  enabled: boolean;
  channels: AutomationChannels;
  titleTemplate: string;
  messageTemplate: string;
  priority: NotificationPriority;
  audienceType: AudienceConfig['type'];
  eventType: EventType;
  updatedAt: Date;
};

export type RecurringSchedule = {
  id: string;
  name: string;
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  audience: Omit<AudienceConfig, 'estimatedCount' | 'resolvedAt'>;
  frequency: 'daily' | 'weekly' | 'monthly';
  timeOfDay: string;
  dayOfWeek: number | null;
  timezone: string;
  enabled: boolean;
  lastRunAt: Date | null;
  nextRunAt: Date | null;
  createdById: string;
  createdByName: string;
};

function mapAutomationRuleRow(row: Record<string, unknown>): AutomationRule {
  const channels = (row.channels as AutomationChannels) ?? {
    push: true,
    in_app: true,
    email: false,
    sms: false,
  };
  return {
    id: String(row.id),
    eventKey: String(row.event_key),
    label: String(row.label),
    description: row.description ? String(row.description) : null,
    enabled: Boolean(row.enabled),
    channels,
    titleTemplate: String(row.title_template),
    messageTemplate: String(row.message_template),
    priority: String(row.priority ?? 'Normal') as NotificationPriority,
    audienceType: String(row.audience_type ?? 'specific_users') as AudienceConfig['type'],
    eventType: String(row.event_type ?? 'none') as EventType,
    updatedAt: parseDate(row.updated_at) ?? new Date(),
  };
}

function mapRecurringScheduleRow(row: Record<string, unknown>): RecurringSchedule {
  return {
    id: String(row.id),
    name: String(row.name),
    title: String(row.title),
    message: String(row.message),
    priority: String(row.priority ?? 'Normal') as NotificationPriority,
    eventType: String(row.event_type ?? 'none') as EventType,
    audience: {
      type: String(row.audience_type ?? 'active_users') as AudienceConfig['type'],
      planId: row.audience_plan_id ? String(row.audience_plan_id) : undefined,
      planName: row.audience_plan_name ? String(row.audience_plan_name) : undefined,
      area: row.audience_area ? String(row.audience_area) : undefined,
      userIds: Array.isArray(row.audience_user_ids)
        ? (row.audience_user_ids as string[]).map(String)
        : undefined,
      userNames: Array.isArray(row.audience_user_names)
        ? (row.audience_user_names as string[]).map(String)
        : undefined,
    },
    frequency: String(row.frequency ?? 'weekly') as RecurringSchedule['frequency'],
    timeOfDay: String(row.time_of_day ?? '09:00'),
    dayOfWeek: row.day_of_week != null ? Number(row.day_of_week) : null,
    timezone: String(row.timezone ?? 'Asia/Kolkata'),
    enabled: Boolean(row.enabled),
    lastRunAt: parseDate(row.last_run_at),
    nextRunAt: parseDate(row.next_run_at),
    createdById: String(row.created_by_id),
    createdByName: String(row.created_by_name),
  };
}

function computeNextRunAtLocal(
  frequency: RecurringSchedule['frequency'],
  timeOfDay: string,
  dayOfWeek: number | null,
): Date {
  const [hours, minutes] = timeOfDay.split(':').map(Number);
  const now = new Date();
  const next = new Date(now);
  next.setHours(hours ?? 9, minutes ?? 0, 0, 0);

  if (frequency === 'daily') {
    if (next <= now) next.setDate(next.getDate() + 1);
    return next;
  }
  if (frequency === 'weekly') {
    const targetDow = dayOfWeek ?? 1;
    const currentDow = next.getDay();
    let daysUntil = (targetDow - currentDow + 7) % 7;
    if (daysUntil === 0 && next <= now) daysUntil = 7;
    next.setDate(next.getDate() + daysUntil);
    return next;
  }
  const targetDay = dayOfWeek ?? 1;
  next.setDate(targetDay);
  if (next <= now) next.setMonth(next.getMonth() + 1);
  return next;
}

export async function fetchAutomationRules(): Promise<AutomationRule[]> {
  const { client } = await requireSession();
  const { data, error } = await client
    .from('notification_automation_rules')
    .select('*')
    .order('label', { ascending: true });
  if (error) throw error;
  return (data ?? []).map((row) => mapAutomationRuleRow(row as Record<string, unknown>));
}

export async function updateAutomationRule(
  id: string,
  patch: Partial<Pick<AutomationRule, 'enabled' | 'channels' | 'titleTemplate' | 'messageTemplate' | 'priority'>>,
): Promise<AutomationRule> {
  const { client } = await requireSession();
  const payload: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.enabled !== undefined) payload.enabled = patch.enabled;
  if (patch.channels !== undefined) payload.channels = patch.channels;
  if (patch.titleTemplate !== undefined) payload.title_template = patch.titleTemplate;
  if (patch.messageTemplate !== undefined) payload.message_template = patch.messageTemplate;
  if (patch.priority !== undefined) payload.priority = patch.priority;

  const { data, error } = await client
    .from('notification_automation_rules')
    .update(payload)
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return mapAutomationRuleRow(data as Record<string, unknown>);
}

export async function fetchRecurringSchedules(): Promise<RecurringSchedule[]> {
  const { client } = await requireSession();
  const { data, error } = await client
    .from('notification_recurring_schedules')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data ?? []).map((row) => mapRecurringScheduleRow(row as Record<string, unknown>));
}

export async function createRecurringSchedule(
  input: Omit<RecurringSchedule, 'id' | 'lastRunAt' | 'nextRunAt' | 'createdById' | 'createdByName'> & {
    createdBy: { id: string; name: string };
  },
): Promise<RecurringSchedule> {
  const { client } = await requireSession();
  const nextRunAt = computeNextRunAtLocal(input.frequency, input.timeOfDay, input.dayOfWeek);
  const { data, error } = await client
    .from('notification_recurring_schedules')
    .insert({
      name: input.name,
      title: input.title,
      message: input.message,
      priority: input.priority,
      event_type: input.eventType,
      audience_type: input.audience.type,
      audience_plan_id: input.audience.planId ?? null,
      audience_plan_name: input.audience.planName ?? null,
      audience_area: input.audience.area ?? null,
      audience_user_ids: input.audience.userIds ?? null,
      audience_user_names: input.audience.userNames ?? null,
      frequency: input.frequency,
      time_of_day: input.timeOfDay,
      day_of_week: input.dayOfWeek,
      timezone: input.timezone,
      enabled: input.enabled,
      next_run_at: nextRunAt.toISOString(),
      created_by_id: input.createdBy.id,
      created_by_name: input.createdBy.name,
    })
    .select('*')
    .single();
  if (error) throw error;
  return mapRecurringScheduleRow(data as Record<string, unknown>);
}

export async function updateRecurringSchedule(
  id: string,
  patch: Partial<
    Pick<
      RecurringSchedule,
      'name' | 'title' | 'message' | 'priority' | 'eventType' | 'audience' | 'frequency' | 'timeOfDay' | 'dayOfWeek' | 'timezone' | 'enabled'
    >
  >,
): Promise<RecurringSchedule> {
  const { client } = await requireSession();
  const payload: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.name !== undefined) payload.name = patch.name;
  if (patch.title !== undefined) payload.title = patch.title;
  if (patch.message !== undefined) payload.message = patch.message;
  if (patch.priority !== undefined) payload.priority = patch.priority;
  if (patch.eventType !== undefined) payload.event_type = patch.eventType;
  if (patch.audience !== undefined) {
    payload.audience_type = patch.audience.type;
    payload.audience_plan_id = patch.audience.planId ?? null;
    payload.audience_plan_name = patch.audience.planName ?? null;
    payload.audience_area = patch.audience.area ?? null;
    payload.audience_user_ids = patch.audience.userIds ?? null;
    payload.audience_user_names = patch.audience.userNames ?? null;
  }
  if (patch.frequency !== undefined) payload.frequency = patch.frequency;
  if (patch.timeOfDay !== undefined) payload.time_of_day = patch.timeOfDay;
  if (patch.dayOfWeek !== undefined) payload.day_of_week = patch.dayOfWeek;
  if (patch.timezone !== undefined) payload.timezone = patch.timezone;
  if (patch.enabled !== undefined) payload.enabled = patch.enabled;

  if (patch.frequency !== undefined || patch.timeOfDay !== undefined || patch.dayOfWeek !== undefined) {
    const freq = patch.frequency ?? 'weekly';
    const time = patch.timeOfDay ?? '09:00';
    const dow = patch.dayOfWeek ?? null;
    payload.next_run_at = computeNextRunAtLocal(freq, time, dow).toISOString();
  }

  const { data, error } = await client
    .from('notification_recurring_schedules')
    .update(payload)
    .eq('id', id)
    .select('*')
    .single();
  if (error) throw error;
  return mapRecurringScheduleRow(data as Record<string, unknown>);
}

export async function deleteRecurringSchedule(id: string): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client.from('notification_recurring_schedules').delete().eq('id', id);
  if (error) throw error;
}

export async function triggerAutoNotification(
  eventKey: string,
  context: {
    audience: Omit<AudienceConfig, 'estimatedCount' | 'resolvedAt'>;
    templateVars?: Record<string, string>;
    title?: string;
    message?: string;
    priority?: NotificationPriority;
    eventType?: EventType;
    linkedRequestId?: string;
    linkedTicketId?: string;
    linkedPlanId?: string;
    deepLinkUrl?: string;
  },
): Promise<AppNotification | null> {
  const { client } = await requireSession();

  const { data: ruleRow, error: ruleErr } = await client
    .from('notification_automation_rules')
    .select('*')
    .eq('event_key', eventKey)
    .maybeSingle();
  if (ruleErr) throw ruleErr;
  if (!ruleRow || !ruleRow.enabled) return null;

  const rule = mapAutomationRuleRow(ruleRow as Record<string, unknown>);
  const vars = context.templateVars ?? {};
  const title = context.title ?? replaceTemplateVars(rule.titleTemplate, vars);
  const message = context.message ?? replaceTemplateVars(rule.messageTemplate, vars);
  const priority = context.priority ?? rule.priority;
  const eventType = context.eventType ?? rule.eventType;

  return sendAutoNotification({
    title,
    message,
    priority,
    eventType,
    audience: context.audience,
    linkedRequestId: context.linkedRequestId,
    linkedTicketId: context.linkedTicketId,
    linkedPlanId: context.linkedPlanId,
    deepLinkUrl: context.deepLinkUrl,
    channels: rule.channels,
  });
}

export async function sendAutoNotification(params: {
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  audience: Omit<AudienceConfig, 'estimatedCount' | 'resolvedAt'>;
  linkedRequestId?: string;
  linkedTicketId?: string;
  linkedPlanId?: string;
  deepLinkUrl?: string;
  channels?: AutomationChannels;
}): Promise<AppNotification> {
  const { client, session } = await requireSession();
  const estimatedCount = await resolveAudienceCount(params.audience);
  const admin = { id: session.user.id, name: session.user.email ?? 'System' };
  const channels = params.channels ?? { push: true, in_app: true, email: false, sms: false };

  const payload = {
    title: params.title,
    message: params.message,
    priority: params.priority,
    event_type: params.eventType,
    status: 'sending',
    audience_type: params.audience.type,
    audience_plan_id: params.audience.planId ?? null,
    audience_plan_name: params.audience.planName ?? null,
    audience_area: params.audience.area ?? null,
    audience_user_ids: params.audience.userIds ?? null,
    audience_user_names: params.audience.userNames ?? null,
    audience_estimated_count: estimatedCount,
    is_draft: false,
    is_auto_generated: true,
    is_scheduled: false,
    linked_request_id: params.linkedRequestId ?? null,
    linked_ticket_id: params.linkedTicketId ?? null,
    linked_plan_id: params.linkedPlanId ?? null,
    deep_link_url: params.deepLinkUrl ?? null,
    created_by_id: admin.id,
    created_by_name: admin.name,
    tags: ['auto'],
    timezone: 'Asia/Kolkata',
  };

  const { data: row, error } = await client.from('broadcast_notifications').insert(payload).select('*').single();
  if (error) throw error;

  const notificationId = String(row.id);
  const { data, error: fnErr } = await client.functions.invoke('send-broadcast-notification', {
    body: {
      notificationId,
      skipPush: !channels.push,
      skipInApp: !channels.in_app,
    },
  });
  if (fnErr) throw new Error(fnErr.message ?? 'Failed to send auto notification');
  if (data && typeof data === 'object' && 'error' in data && data.error) {
    throw new Error(String(data.error));
  }

  return fetchNotificationById(notificationId);
}

export async function fetchTemplates(): Promise<NotificationTemplate[]> {
  const { client } = await requireSession();
  const { data, error } = await client.from('notification_templates').select('*').order('created_at', { ascending: true });
  if (error) throw error;
  return (data ?? []).map((row) => ({
    id: String(row.id),
    name: String(row.name),
    title: String(row.title),
    message: String(row.message),
    priority: String(row.priority) as NotificationPriority,
    eventType: String(row.event_type) as EventType,
    audienceType: String(row.audience_type) as NotificationTemplate['audienceType'],
    isSystem: Boolean(row.is_system),
    createdAt: parseDate(row.created_at) ?? new Date(),
  }));
}

export async function saveAsTemplate(data: {
  name: string;
  title: string;
  message: string;
  priority: NotificationPriority;
  eventType: EventType;
  audienceType: NotificationTemplate['audienceType'];
}): Promise<NotificationTemplate> {
  const { client } = await requireSession();
  const { data: row, error } = await client
    .from('notification_templates')
    .insert({
      name: data.name,
      title: data.title,
      message: data.message,
      priority: data.priority,
      event_type: data.eventType,
      audience_type: data.audienceType,
      is_system: false,
    })
    .select('*')
    .single();
  if (error) throw error;
  return {
    id: String(row.id),
    name: String(row.name),
    title: String(row.title),
    message: String(row.message),
    priority: String(row.priority) as NotificationPriority,
    eventType: String(row.event_type) as EventType,
    audienceType: String(row.audience_type) as NotificationTemplate['audienceType'],
    isSystem: false,
    createdAt: parseDate(row.created_at) ?? new Date(),
  };
}

export async function deleteTemplate(id: string): Promise<void> {
  const { client } = await requireSession();
  const { error } = await client.from('notification_templates').delete().eq('id', id).eq('is_system', false);
  if (error) throw error;
}

export async function registerPushToken(
  userId: string,
  userType: string,
  pushToken: string,
  planId?: string,
  area?: string,
): Promise<void> {
  await registerFcmToken(userId, pushToken, { userType, planId, area });
}

export async function deregisterPushToken(userId: string, pushToken: string): Promise<void> {
  const client = getSupabase();
  const { error } = await client
    .from('user_fcm_tokens')
    .update({ is_active: false, updated_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('token', pushToken);
  if (error) throw error;
}

export async function updateUserPushTokenMetadata(userId: string, planId?: string, area?: string): Promise<void> {
  const client = getSupabase();
  const patch: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (planId) patch.plan_id = planId;
  if (area) patch.area = area;
  const { error } = await client.from('user_fcm_tokens').update(patch).eq('user_id', userId);
  if (error) throw error;
}

export async function fetchNotificationStats(): Promise<{
  totalSent: number;
  totalDrafts: number;
  avgDeliveryRate: number;
  avgOpenRate: number;
  totalRecipients: number;
  sentThisMonth: number;
  lastSent: AppNotification | null;
  byPriority: Record<NotificationPriority, number>;
  byEventType: Record<string, number>;
}> {
  const all = await fetchNotifications();
  const sent = all.filter((n) => !n.isDraft && n.status !== 'draft');
  const drafts = all.filter((n) => n.isDraft);
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const sentThisMonth = sent.filter((n) => n.schedule.sentAt && n.schedule.sentAt >= monthStart).length;
  const withDelivery = sent.filter((n) => n.delivery);
  const avgDeliveryRate =
    withDelivery.length > 0
      ? withDelivery.reduce((s, n) => s + (n.delivery?.deliveryRate ?? 0), 0) / withDelivery.length
      : 0;
  const avgOpenRate =
    withDelivery.length > 0
      ? withDelivery.reduce((s, n) => s + (n.delivery?.openRate ?? 0), 0) / withDelivery.length
      : 0;
  const totalRecipients = sent.reduce((s, n) => s + (n.delivery?.totalTargeted ?? 0), 0);

  const byPriority: Record<NotificationPriority, number> = { Low: 0, Normal: 0, High: 0, Urgent: 0 };
  const byEventType: Record<string, number> = {};
  for (const n of sent) {
    byPriority[n.priority] += 1;
    byEventType[n.eventType] = (byEventType[n.eventType] ?? 0) + 1;
  }

  const lastSent = sent.sort((a, b) => (b.schedule.sentAt?.getTime() ?? 0) - (a.schedule.sentAt?.getTime() ?? 0))[0] ?? null;

  return {
    totalSent: sent.length,
    totalDrafts: drafts.length,
    avgDeliveryRate,
    avgOpenRate,
    totalRecipients,
    sentThisMonth,
    lastSent,
    byPriority,
    byEventType,
  };
}

export async function recoverStuckSendingNotifications(): Promise<number> {
  if (broadcastTableUnavailable) return 0;

  try {
    const { client } = await requireSession();
    const cutoff = new Date(Date.now() - 5 * 60 * 1000).toISOString();
    const { data, error } = await client
      .from('broadcast_notifications')
      .select('id')
      .eq('status', 'sending')
      .lt('updated_at', cutoff);
    if (error) {
      if (isMissingBroadcastTable(error)) {
        broadcastTableUnavailable = true;
        return 0;
      }
      throw error;
    }
    if (!data?.length) return 0;

    const ids = data.map((r) => String(r.id));
    const { error: updateErr } = await client
      .from('broadcast_notifications')
      .update({ status: 'partially_failed', updated_at: new Date().toISOString() })
      .in('id', ids);
    if (updateErr) throw updateErr;
    return ids.length;
  } catch {
    return 0;
  }
}

export function subscribeToNotifications(callback: (notifications: AppNotification[]) => void): () => void {
  if (notificationsRealtimeFailed || broadcastTableUnavailable) {
    void fetchNotifications().then(callback).catch(() => undefined);
    return () => {};
  }

  const client = getSupabase();
  notificationsRealtimeListeners.add(callback);

  if (!notificationsRealtimeChannel) {
    notificationsRealtimeChannel = client
      .channel('admin-broadcast-notifications')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'broadcast_notifications' }, () => {
        void notifyNotificationsRealtimeListeners();
      })
      .subscribe((status) => {
        if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT') {
          notificationsRealtimeFailed = true;
        }
      });
  }

  void fetchNotifications().then(callback).catch(() => undefined);

  return () => {
    notificationsRealtimeListeners.delete(callback);
    if (notificationsRealtimeListeners.size === 0 && notificationsRealtimeChannel) {
      void client.removeChannel(notificationsRealtimeChannel);
      notificationsRealtimeChannel = null;
    }
  };
}

export const broadcastNotificationService = {
  fetchNotifications,
  fetchDrafts,
  fetchSentHistory,
  fetchNotificationById,
  createNotification,
  updateNotification,
  saveDraft,
  deleteDraft,
  deleteFromHistory,
  scheduleNotification,
  cancelScheduled,
  fetchDueScheduledNotifications,
  sendNotification,
  resendNotification,
  sendAutoNotification,
  triggerAutoNotification,
  fetchAutomationRules,
  updateAutomationRule,
  fetchRecurringSchedules,
  createRecurringSchedule,
  updateRecurringSchedule,
  deleteRecurringSchedule,
  fetchTemplates,
  saveAsTemplate,
  deleteTemplate,
  registerPushToken,
  deregisterPushToken,
  updateUserPushTokenMetadata,
  fetchNotificationStats,
  recoverStuckSendingNotifications,
  subscribeToNotifications,
};
