export {
  useGetAdminOfficerStatsQuery,
  useGetAdminOfficersQuery,
  useGetAdminOfficerDetailQuery,
  useGetOfficerProfileQuery,
  useGetOfficerContractQuery,
  useGetOfficerDocumentsQuery,
  useGetOfficerRolePermissionsQuery,
  useGetOfficerRolesQuery,
  useCreateAdminOfficerMutation,
  useUpdateOfficerPersonalMutation,
  useUpdateOfficerContactMutation,
  useUpdateOfficerContractMutation,
  useUpdateOfficerRoleMutation,
  useUpdateAdminOfficerMutation,
  useBlockOfficerMutation,
  useUnblockOfficerMutation,
  useDeleteOfficerMutation,
  useUploadOfficerDocumentMutation,
  useUploadAdditionalOfficerDocumentMutation,
  useDeleteOfficerDocumentMutation,
  useLazyGetOfficerDocumentSignedUrlQuery,
  useRevealOfficerPasswordMutation,
  useResetOfficerPasswordMutation,
  useGetOfficerPerformanceQuery,
  useGetOfficerPayslipsQuery,
  useGetOfficerAssignedInventoryQuery,
} from '@/services/api/adminOfficersApi';
